### ISSUE TITLE
Can I use your manualCheckDataset in my paper？

### ISSUE THREAD

**Issue by smartcontract-detect-yzu** [xf97/HuangGai#3]
I think it's a great job, and can I  use your manualCheckDataset in my paper？

**Comment by xf97** [comment]
Of course you can do that, you can use it as the dataset of your paper's evaluation, but not your paper's contributions.


Hope your paper gets a good result.&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xf97/HuangGai"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月2日(星期二) 中午11:02
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[xf97/HuangGai] Can I use your manualCheckDataset in my paper？ (Issue #3)





 
I think it's a great job, and can I  use your manualCheckDataset in my paper？
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
